# Generated by Django 4.1.1 on 2022-09-15 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=32)),
                ('operation_type', models.CharField(max_length=32)),
                ('entry', models.CharField(max_length=32)),
                ('datetime', models.DateField()),
                ('source', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='fav_color',
        ),
        migrations.AddField(
            model_name='customuser',
            name='currency',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='source',
            field=models.CharField(default='both', max_length=50),
        ),
        migrations.CreateModel(
            name='TakeProfit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entry', models.CharField(max_length=32)),
                ('advice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.advice')),
            ],
        ),
        migrations.CreateModel(
            name='StopLoss',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entry', models.CharField(max_length=32)),
                ('advice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.advice')),
            ],
        ),
    ]
