# Generated by Django 4.1.1 on 2022-09-15 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_delete_note'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advice',
            table='advice',
        ),
        migrations.AlterModelTable(
            name='stoploss',
            table='stoploss',
        ),
        migrations.AlterModelTable(
            name='takeprofit',
            table='takeProfit',
        ),
    ]
