# Generated by Django 4.1.1 on 2022-09-15 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_advice_table_alter_stoploss_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoploss',
            name='advice',
            field=models.ForeignKey(db_column='advice_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.advice'),
        ),
        migrations.AlterField(
            model_name='takeprofit',
            name='advice',
            field=models.ForeignKey(db_column='advice_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.advice'),
        ),
    ]
